#!/bin/bash

# To update the version shipped in this quickstart, bump this variable:
#
install_version="3.9.1"

# Download and install Wordpress

install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}

# Used in this script only
current_version_dir=${OPENSHIFT_DATA_DIR}current

#
# If WordPress is already installed in the current gear, there
# is nothing to build :-)
#
[ -d "${current_version_dir}" ] && exit 0

mkdir -p $install_dir

pushd ${install_dir} >/dev/null
curl -s http://wordpress.org/wordpress-3.9.1.tar.gz > wordpress-3.9.1.tar.gz
#curl -s http://ar.wordpress.org/wordpress-3.9.1-ar.tar.gz > wordpress-3.9.1-ar.tar.gz

# Verify the sources
#
#tarball_md5=$(md5sum wordpress-3.9.1-ar.tar.gz | cut -d ' ' -f 1)
tarball_md5=$(md5sum wordpress-3.9.1.tar.gz | cut -d ' ' -f 1)
#wordpress_md5=$(curl -s http://ar.wordpress.org/wordpress-3.9.1-ar.tar.gz.md5)
wordpress_md5=$(curl -s http://wordpress.org/wordpress-3.9.1.tar.gz.md5)

if [ "${tarball_md5}" != "${wordpress_md5}" ]; then
  echo "ERROR: Wordpress ${install_version} MD5 checksum mismatch."
  exit 1;
fi

# Install Wordpress
#
#tar --strip-components=1 -xzf wordpress-3.9.1-ar.tar.gz
tar --strip-components=1 -xzf wordpress-3.9.1.tar.gz
#rm -rf wordpress-3.9.1-ar.tar.gz
rm -rf wordpress-3.9.1.tar.gz
echo $install_version > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version

popd >/dev/null
